INSERT INTO subject (subject_name)
VALUES
('Steel Structures'),
('Concrete Structures'),
('Foundation Engineering'),
('Soil Mechanics'),
('Fluid Mechanics'),
('Heat Transfer'),
('Manufacturing Systems'),
('CNC Machining'),
('Power Generation and Distribution'),
('Renewable Energy Systems'),
('Automatic Control Systems'),
('Robotics and Automation'),
('Molecular Biology'),
('Cell Physiology'),
('Human Genetics'),
('Molecular Genetics'),
('Organic Synthesis'),
('Spectroscopy'),
('Instrumental Analysis'),
('Chromatography Techniques'),
('Quantum Physics'),
('Quantum Field Theory'),
('Electrodynamics'),
('Optics and Photonics'),
('Algorithm Design and Analysis'),
('Data Structures and Algorithms in Java'),
('Database Design and Management'),
('SQL and Relational Databases'),
('Network Security'),
('Cryptography and Data Protection'),
('Business Process Modeling'),
('Process Optimization and Automation'),
('Software Requirements Engineering'),
('Software Design Patterns'),
('Software Testing Techniques'),
('Test Automation and Performance Testing');